name: Auto-update formulae/casks
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: '0 */12 * * *' # Run twice daily
  release:
    types: [published]

jobs:
  update-formulae:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Update formulae
        uses: dawidd6/action-homebrew-bump-formula@v5
        with:
          token: ${{ secrets.TOKEN }}
          tap: ${{ github.repository }}
          livecheck: true
          user_name: "Martin Mauch"
          user_email: "martin.mauch@gmail.com"
          force: false

  update-casks:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Update casks
        uses: eugenesvk/action-homebrew-bump-cask@a05fd49892799eade237259963d787ba0143dab1
        with:
          token: ${{ secrets.TOKEN }}
          tap: ${{ github.repository }}
          livecheck: true
          force: false
